# Main AlertManager Configuration
# This file combines all the routing, inhibition, and receiver configurations

global:
  # ResolveTimeout is the time after which an alert is declared resolved
  # if it has not been updated.
  resolve_timeout: 5m
  
  # SMTP configuration
  smtp_from: 'alertmanager@company.com'
  smtp_smarthost: 'smtp.company.com:587'
  smtp_auth_username: 'alertmanager@company.com'
  smtp_auth_password_file: '/etc/alertmanager/smtp-password'
  smtp_require_tls: true
  
  # Slack configuration  
  slack_api_url_file: '/etc/alertmanager/slack-default-webhook'
  
  # PagerDuty configuration
  pagerduty_url: 'https://events.pagerduty.com/v2/enqueue'
  
  # HTTP configuration
  http_config:
    proxy_url: 'http://proxy.company.com:8080'
    no_proxy: 'localhost,127.0.0.1,internal.company.com'

# Include routing rules from separate file
# Note: In production, you would merge these files or use a configuration management tool
# The routing rules are defined in ./configs/routing-rules.yaml

# Include inhibition rules from separate file
# The inhibition rules are defined in ./configs/inhibition-rules.yaml

# Include receivers from separate file
# The receivers are defined in ./configs/receivers.yaml

# Templates for notifications
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Main configuration structure (simplified for demonstration)
# In production, you would merge the contents of the separate files here
route:
  receiver: 'default-receiver'
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h

receivers:
  - name: 'default-receiver'
    email_configs:
      - to: 'alerts@company.com'

inhibit_rules: []