apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: default
spec:
  selector:
    app: alertmanager
  ports:
  - port: 9093
    targetPort: 9093
    protocol: TCP
    name: http
  type: ClusterIP