---
# YAML Linting Configuration
extends: default

rules:
  # Line length
  line-length:
    max: 120
    level: warning

  # Indentation
  indentation:
    spaces: 2
    indent-sequences: true

  # Comments
  comments:
    require-starting-space: true
    min-spaces-from-content: 1

  # Empty lines
  empty-lines:
    max: 2
    max-start: 0
    max-end: 0

  # Trailing spaces
  trailing-spaces: enable

  # Document start
  document-start:
    present: false

  # Truthy values
  truthy:
    allowed-values: ['true', 'false', 'on', 'off', 'yes', 'no']

  # Brackets
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1

  # Braces
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

# Ignore paths
ignore: |
  vendor/
  .git/
  dist/
  coverage/
  *.generated.yaml
  *.generated.yml