apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: monitoring
type: Opaque
stringData:
  # Change this password before deploying to production!
  # You can generate a strong password with: openssl rand -base64 32
  admin-password: "changeme123!"