apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  type: ClusterIP
  selector:
    app: grafana
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
---
# Optional: Uncomment to expose Grafana externally via LoadBalancer
# apiVersion: v1
# kind: Service
# metadata:
#   name: grafana-external
#   namespace: monitoring
#   labels:
#     app: grafana
#   annotations:
#     # Add cloud-specific annotations here if needed
#     # For AWS: service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
#     # For GCP: cloud.google.com/load-balancer-type: "External"
# spec:
#   type: LoadBalancer
#   selector:
#     app: grafana
#   ports:
#   - name: http
#     port: 80
#     targetPort: 3000
#     protocol: TCP