apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: default
spec:
  selector:
    app: loki
  ports:
  - port: 3100
    targetPort: 3100
    protocol: TCP
    name: http-metrics
  type: ClusterIP