apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  namespace: default
spec:
  selector:
    app: jaeger
  ports:
  - port: 16686
    targetPort: 16686
    protocol: TCP
    name: query-http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: default
spec:
  selector:
    app: jaeger
  ports:
  - port: 14268
    targetPort: 14268
    protocol: TCP
    name: collector-http
  - port: 14250
    targetPort: 14250
    protocol: TCP
    name: collector-grpc
  - port: 9411
    targetPort: 9411
    protocol: TCP
    name: zipkin
  - port: 4317
    targetPort: 4317
    protocol: TCP
    name: otlp-grpc
  - port: 4318
    targetPort: 4318
    protocol: TCP
    name: otlp-http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-agent
  namespace: default
spec:
  selector:
    app: jaeger
  ports:
  - port: 5775
    targetPort: 5775
    protocol: UDP
    name: zk-compact-trft
  - port: 6831
    targetPort: 6831
    protocol: UDP
    name: jg-compact-trft
  - port: 6832
    targetPort: 6832
    protocol: UDP
    name: jg-binary-trft
  - port: 5778
    targetPort: 5778
    protocol: TCP
    name: config-rest
  type: ClusterIP