# Jekyll configuration for GitHub Pages
title: APM - Application Performance Monitoring for GoFiber
description: >-
  Comprehensive APM solution for GoFiber applications with metrics, tracing, 
  logging, and cloud deployment capabilities
baseurl: "/apm" # the subpath of your site, e.g. /blog
url: "https://chaksack.github.io" # the base hostname & protocol for your site

# Build settings
theme: jekyll-theme-cayman
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# GitHub metadata
github:
  repository_url: https://github.com/chaksack/apm
  repository_name: apm
  owner_url: https://github.com/chaksack
  owner_name: chaksack

# Navigation
navigation:
  - title: Home
    url: /
  - title: Quick Start
    url: /quickstart
  - title: Documentation
    url: /documentation
  - title: CLI Reference
    url: /cli-reference
  - title: API Reference
    url: https://pkg.go.dev/github.com/chaksack/apm
  - title: GitHub
    url: https://github.com/chaksack/apm

# Analytics (optional - add your tracking ID)
# google_analytics: UA-XXXXXXXXX-X

# Social links
social:
  - platform: github
    url: https://github.com/chaksack/apm
  - platform: email
    url: mailto:chakdahah@gmail.com