apiVersion: 1

datasources:
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger-query.monitoring.svc.cluster.local:16686
    uid: jaeger
    jsonData:
      tracesToLogs:
        datasourceUid: loki
        tags: ["cluster", "namespace", "pod"]
        mappedTags:
          - key: service.name
            value: app
        spanStartTimeShift: "-1h"
        spanEndTimeShift: "1h"
        filterByTraceID: true
        filterBySpanID: false
        lokiSearch: true
    editable: true